<head>
    <title>The Bird Home Page</title>
    <meta charset="utf-8"/>
    <meta name="author" content="Martin Dwyer"/>
    <meta name="Keywords" content="Bromwich Farms Home Page"/>
    <meta name="Description" content="Home page for grower of Iowa vegetables."/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

    <?php require_once('styles.php') ?>

</head>
